services:
  scillm-proxy:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.scillm
    command: ["sh","-lc","scillm-proxy start --host 0.0.0.0 --port 4000"]
    environment:
      - LITELLM_MODE=PRODUCTION
      - LITELLM_ENABLE_CODEWORLD=1
      - LITELLM_ENABLE_LEAN4=1
    ports:
      - "4000:4000"
    depends_on:
      - codeworld-bridge
      - lean4-bridge

  codeworld-bridge:
    build:
      context: ../..
    dockerfile: deploy/docker/Dockerfile.scillm
    command: ["sh","-lc","PYTHONPATH=src uvicorn codeworld.bridge.server:app --host 0.0.0.0 --port 8887"]
    ports:
      - "8887:8887"

  lean4-bridge:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.scillm
    command: ["sh","-lc","PYTHONPATH=src uvicorn lean4_prover.bridge.server:app --host 0.0.0.0 --port 8787"]
    environment:
      - LEAN4_BRIDGE_TIMEOUT_SECONDS=300
    ports:
      - "8787:8787"
    volumes:
      []

