services:
  scillm-proxy:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.scillm
    command: ["sh","-lc","scillm-proxy start --host 0.0.0.0 --port 4000"]
    environment:
      - LITELLM_MODE=PRODUCTION
    ports:
      - "4000:4000"

