"""Adversarial blind e2e tests for the scillm proxy.

Generated by /test-lab — all tests hit the live proxy at localhost:4001.
Zero mocks. Tests exercise edge cases, race conditions, and contract violations
that the primary e2e suite does not cover.

Focus areas:
  1. Router fallback cascade (text → text-deepseek → text-gemini)
  2. JSON guard (malformed JSON repair)
  3. Budget endpoint contract
  4. Concurrency guard queuing behavior
  5. VLM auto-routing (image_url detection)
  6. Auth enforcement (missing/invalid Bearer tokens)
  7. Streaming SSE contract
  8. Error propagation (provider down scenarios)
  9. Source grounding verification (batch engine integration)
"""
from __future__ import annotations

import asyncio
import base64
import json
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

import httpx
import pytest


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _chat(client: httpx.Client, model: str, content: str | list, **kw) -> httpx.Response:
    if isinstance(content, str):
        messages = [{"role": "user", "content": content}]
    else:
        messages = [{"role": "user", "content": content}]
    payload = {"model": model, "messages": messages, "max_tokens": 16, "temperature": 0, **kw}
    return client.post("/v1/chat/completions", json=payload, timeout=45.0)


def _chat_raw(base_url: str, headers: dict, model: str, content: str, **kw) -> httpx.Response:
    """POST without pre-configured client — for auth edge-case tests."""
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": content}],
        "max_tokens": 4,
        **kw,
    }
    return httpx.post(
        f"{base_url}/v1/chat/completions",
        json=payload,
        headers=headers,
        timeout=15.0,
    )


# ===================================================================
# 1. FALLBACK CASCADE — verify cascade order and exhaustion
# ===================================================================


class TestFallbackCascade:
    """Verify fallback chain text → text-deepseek → text-gemini works."""

    def test_fallback_chain_declared_in_health(self, client: httpx.Client):
        """Health endpoint must expose the exact fallback ordering."""
        data = client.get("/v1/scillm/health").json()
        fb = data.get("fallbacks", {})
        assert "text" in fb, "text group must declare fallbacks"
        chain = fb["text"]
        assert chain == ["text-deepseek", "text-gemini"], f"Unexpected chain: {chain}"

    def test_vlm_fallback_chain_declared(self, client: httpx.Client):
        """VLM group must declare its own fallback chain."""
        data = client.get("/v1/scillm/health").json()
        fb = data.get("fallbacks", {})
        assert "vlm" in fb, "vlm group must declare fallbacks"
        assert "vlm-openrouter" in fb["vlm"], f"vlm chain: {fb['vlm']}"

    def test_tail_of_cascade_responds(self, client: httpx.Client, any_model_live: str | None):
        """text-gemini (tail of cascade) should respond independently."""
        if any_model_live is None:
            pytest.skip("No live backend")
        r = _chat(client, "text-gemini", "Reply with exactly: PONG")
        # May fail if Gemini key is bad, but should NOT return "unknown model"
        if r.status_code >= 400:
            assert "unknown" not in r.text.lower(), "text-gemini not recognized as model"

    def test_cascade_retries_expose_retry_policy(self, client: httpx.Client):
        """Retry policy must be present in health with expected keys."""
        data = client.get("/v1/scillm/health").json()
        rp = data.get("retry_policy", {})
        assert "internal_server_error" in rp, f"retry_policy missing 5xx key: {rp}"
        assert "rate_limit_error" in rp, f"retry_policy missing 429 key: {rp}"
        assert rp["internal_server_error"] >= 1, "5xx retries should be >= 1"


# ===================================================================
# 2. JSON GUARD — response_format enforcement and repair
# ===================================================================


class TestJsonGuard:
    """Verify JSON guard validates/repairs responses when json_object requested."""

    def test_json_mode_returns_valid_json(self, client: httpx.Client, any_model_live: str | None):
        """Requesting json_object mode must produce parseable JSON content."""
        if any_model_live is None:
            pytest.skip("No live backend")
        r = _chat(
            client,
            any_model_live,
            'Return a JSON object with key "status" and value "ok".',
            response_format={"type": "json_object"},
        )
        if r.status_code == 200:
            data = r.json()
            content = data["choices"][0]["message"]["content"]
            parsed = json.loads(content)  # must not raise
            assert isinstance(parsed, dict), f"Expected dict, got {type(parsed)}"

    def test_json_mode_without_json_instruction(self, client: httpx.Client, any_model_live: str | None):
        """JSON mode with a non-JSON prompt should still return valid JSON or error cleanly."""
        if any_model_live is None:
            pytest.skip("No live backend")
        r = _chat(
            client,
            any_model_live,
            "Tell me about the weather today.",
            response_format={"type": "json_object"},
        )
        if r.status_code == 200:
            data = r.json()
            content = data["choices"][0]["message"]["content"]
            if content is not None:
                # JSON guard should ensure this is valid JSON or the proxy retries/errors
                try:
                    json.loads(content)
                except json.JSONDecodeError:
                    pytest.fail(f"JSON guard let through invalid JSON: {content[:200]}")
        elif r.status_code == 502:
            # 502 = json_validation_error is acceptable (guard caught and rejected)
            data = r.json()
            assert "json" in data.get("error", {}).get("type", "").lower() or \
                   "json" in data.get("error", {}).get("message", "").lower(), \
                   f"502 should mention JSON: {data}"

    def test_non_json_mode_passes_through(self, client: httpx.Client, any_model_live: str | None):
        """Without json_object mode, prose responses pass through unchanged."""
        if any_model_live is None:
            pytest.skip("No live backend")
        r = _chat(client, any_model_live, "Say hello in one word.")
        if r.status_code == 200:
            content = r.json()["choices"][0]["message"]["content"]
            assert len(content) > 0, "Response should have content"


# ===================================================================
# 3. BUDGET ENDPOINT CONTRACT — deep schema validation
# ===================================================================


class TestBudgetContract:
    """Deep validation of /v1/budget endpoint schema and behavior."""

    def test_budget_returns_200(self, client: httpx.Client):
        r = client.get("/v1/budget")
        assert r.status_code == 200

    def test_budget_schema_when_loaded(self, client: httpx.Client):
        """If budget_guard is loaded, response must have full schema."""
        data = client.get("/v1/budget").json()
        if data.get("status") == "budget_guard_not_loaded":
            pytest.skip("Budget guard not loaded")
        for key in ("daily_limit", "remaining", "reset_at"):
            assert key in data, f"Budget response missing '{key}': {data}"
        assert isinstance(data["remaining"], (int, float))
        assert isinstance(data["daily_limit"], (int, float))

    def test_budget_requires_auth(self, proxy_base: str):
        """Budget endpoint without auth must return 401."""
        r = httpx.get(f"{proxy_base}/v1/budget", timeout=10.0)
        assert r.status_code == 401

    def test_budget_idempotent(self, client: httpx.Client):
        """Two rapid budget calls return same structure."""
        r1 = client.get("/v1/budget").json()
        r2 = client.get("/v1/budget").json()
        assert set(r1.keys()) == set(r2.keys()), "Budget keys changed between calls"


# ===================================================================
# 4. CONCURRENCY GUARD — queuing under load
# ===================================================================


class TestConcurrencyGuard:
    """Verify concurrency guard queues overflow instead of rejecting."""

    def test_concurrent_requests_complete(self, client: httpx.Client, any_model_live: str | None):
        """Multiple concurrent requests should all eventually complete (queued, not rejected)."""
        if any_model_live is None:
            pytest.skip("No live backend")
        n = 3  # modest concurrency — enough to exercise queue without overloading

        def _do_one(i: int) -> tuple[int, int]:
            r = _chat(client, any_model_live, f"Reply: {i}")
            return i, r.status_code

        with ThreadPoolExecutor(max_workers=n) as pool:
            futures = [pool.submit(_do_one, i) for i in range(n)]
            results = [f.result(timeout=60) for f in as_completed(futures)]

        statuses = [s for _, s in results]
        # All should succeed or at least not be 429 (queued, not rejected)
        for idx, status in results:
            assert status != 429, f"Request {idx} got 429 — guard rejected instead of queuing"

    def test_concurrency_status_in_health(self, client: httpx.Client):
        """Health endpoint should expose concurrency slot info if guard is loaded."""
        data = client.get("/v1/scillm/health").json()
        # concurrency field is optional — if present, validate structure
        if "concurrency" in data and data["concurrency"]:
            conc = data["concurrency"]
            assert isinstance(conc, dict), f"Expected dict, got {type(conc)}"


# ===================================================================
# 5. VLM AUTO-ROUTING — adversarial image detection
# ===================================================================


class TestVlmAutoRoutingAdversarial:
    """Adversarial VLM routing tests — edge cases the basic suite misses."""

    def test_nested_image_url_detected(self, client: httpx.Client):
        """image_url buried in multi-part content should still trigger VLM routing."""
        content = [
            {"type": "text", "text": "First, here's context."},
            {"type": "text", "text": "Now analyze this image:"},
            {"type": "image_url", "image_url": {"url": "https://example.com/chart.png"}},
        ]
        r = _chat(client, "text", content)
        # Should not crash, should attempt VLM routing
        assert r.status_code > 0

    def test_text_with_image_word_not_rerouted(self, client: httpx.Client, any_model_live: str | None):
        """The word 'image' in text should NOT trigger VLM routing."""
        if any_model_live is None:
            pytest.skip("No live backend")
        r = _chat(client, any_model_live, "Describe what an image classification model does.")
        # Should succeed on text model, not reroute to vlm
        if r.status_code == 200:
            data = r.json()
            content = data["choices"][0]["message"]["content"]
            assert content is None or len(content) > 0

    def test_empty_content_list_no_crash(self, client: httpx.Client):
        """Empty content list should return error, not crash."""
        payload = {
            "model": "text",
            "messages": [{"role": "user", "content": []}],
            "max_tokens": 4,
        }
        r = client.post("/v1/chat/completions", json=payload, timeout=15.0)
        # Should error cleanly (empty messages or content validation)
        assert r.status_code > 0


# ===================================================================
# 6. AUTH ENFORCEMENT — adversarial edge cases
# ===================================================================


class TestAuthAdversarial:
    """Adversarial auth tests — edge cases beyond basic 401 checks."""

    def test_empty_bearer_token(self, proxy_base: str):
        """Bearer with empty string must be rejected."""
        try:
            r = _chat_raw(proxy_base, {"Authorization": "Bearer "}, "text", "hi")
            assert r.status_code == 401
        except httpx.LocalProtocolError:
            # httpx rejects illegal header values client-side — acceptable
            pass

    def test_bearer_with_extra_spaces(self, proxy_base: str):
        """Bearer token with trailing/leading whitespace should still work."""
        try:
            r = _chat_raw(proxy_base, {"Authorization": "Bearer  sk-dev-proxy-123 "}, "text", "hi")
            # Whitespace-trimmed token should match — implementation dependent
            # Accept either 200 (trimmed match) or 401 (strict match)
            assert r.status_code in (200, 401, 400, 500, 502, 503)
        except httpx.LocalProtocolError:
            # httpx rejects illegal header values client-side — acceptable
            pass

    def test_basic_auth_not_accepted(self, proxy_base: str):
        """HTTP Basic Auth should NOT work — only Bearer tokens."""
        creds = base64.b64encode(b"admin:sk-dev-proxy-123").decode()
        r = _chat_raw(proxy_base, {"Authorization": f"Basic {creds}"}, "text", "hi")
        assert r.status_code == 401

    def test_auth_on_ops_endpoints(self, proxy_base: str):
        """All /v1/scillm/* and /v1/budget endpoints require auth."""
        for path in ("/v1/scillm/health", "/v1/scillm/models", "/v1/budget", "/v1/models"):
            r = httpx.get(f"{proxy_base}{path}", timeout=10.0)
            assert r.status_code == 401, f"{path} returned {r.status_code} without auth"

    def test_health_liveliness_no_auth_required(self, proxy_base: str):
        """/health/liveliness should work without auth (Docker healthcheck)."""
        r = httpx.get(f"{proxy_base}/health/liveliness", timeout=10.0)
        assert r.status_code == 200


# ===================================================================
# 7. STREAMING SSE — adversarial validation
# ===================================================================


class TestStreamingAdversarial:
    """Adversarial streaming tests — format strictness and edge cases."""

    def test_stream_chunks_have_required_fields(self, client: httpx.Client, any_model_live: str | None):
        """Every SSE chunk must have id, object, choices fields."""
        if any_model_live is None:
            pytest.skip("No live backend")
        with client.stream(
            "POST",
            "/v1/chat/completions",
            json={
                "model": any_model_live,
                "messages": [{"role": "user", "content": "Count 1 2 3"}],
                "max_tokens": 16,
                "stream": True,
            },
            timeout=30.0,
        ) as r:
            assert r.status_code == 200
            for line in r.iter_lines():
                if not line or line.startswith(":"):
                    continue
                assert line.startswith("data: "), f"Bad SSE line: {line[:80]}"
                payload = line[len("data: "):]
                if payload.strip() == "[DONE]":
                    break
                chunk = json.loads(payload)
                assert "id" in chunk, f"Chunk missing 'id': {chunk}"
                assert "object" in chunk, f"Chunk missing 'object': {chunk}"
                assert "choices" in chunk, f"Chunk missing 'choices': {chunk}"

    def test_stream_content_type_is_sse(self, client: httpx.Client, any_model_live: str | None):
        """Streaming response Content-Type must be text/event-stream."""
        if any_model_live is None:
            pytest.skip("No live backend")
        with client.stream(
            "POST",
            "/v1/chat/completions",
            json={
                "model": any_model_live,
                "messages": [{"role": "user", "content": "Hi"}],
                "max_tokens": 4,
                "stream": True,
            },
            timeout=30.0,
        ) as r:
            if r.status_code == 200:
                ct = r.headers.get("content-type", "")
                assert "text/event-stream" in ct, f"Expected SSE content-type, got: {ct}"

    def test_non_stream_content_type_is_json(self, client: httpx.Client, any_model_live: str | None):
        """Non-streaming response Content-Type must be application/json."""
        if any_model_live is None:
            pytest.skip("No live backend")
        r = _chat(client, any_model_live, "Hi")
        if r.status_code == 200:
            ct = r.headers.get("content-type", "")
            assert "application/json" in ct, f"Expected JSON content-type, got: {ct}"

    def test_stream_false_does_not_stream(self, client: httpx.Client, any_model_live: str | None):
        """Explicit stream=false must return complete JSON, not SSE."""
        if any_model_live is None:
            pytest.skip("No live backend")
        r = _chat(client, any_model_live, "Hi", stream=False)
        if r.status_code == 200:
            data = r.json()
            assert "choices" in data
            assert "message" in data["choices"][0], "Non-stream must have message, not delta"


# ===================================================================
# 8. ERROR PROPAGATION — adversarial error handling
# ===================================================================


class TestErrorPropagationAdversarial:
    """Adversarial error propagation — unknown routes, bad payloads."""

    def test_unknown_route_returns_404(self, client: httpx.Client):
        """Catch-all should return 404 for unknown paths."""
        r = client.get("/v1/nonexistent/endpoint")
        assert r.status_code == 404
        data = r.json()
        assert "error" in data

    def test_post_to_get_endpoint_is_handled(self, client: httpx.Client):
        """POST to a GET-only endpoint should not crash."""
        r = client.post("/health/liveliness", json={})
        # FastAPI returns 405 Method Not Allowed or the catch-all handles it
        assert r.status_code in (200, 405, 404)

    def test_oversized_payload_handled(self, client: httpx.Client):
        """Very large payload should be rejected, not crash the proxy."""
        huge_content = "x" * 100_000  # 100KB of text
        r = _chat(client, "text", huge_content)
        # Accept any response — the point is it doesn't hang or crash
        assert r.status_code > 0

    def test_unicode_in_messages(self, client: httpx.Client, any_model_live: str | None):
        """Unicode, emoji, and special chars must not crash the proxy."""
        if any_model_live is None:
            pytest.skip("No live backend")
        r = _chat(client, any_model_live, "Hello 🌍 你好 مرحبا Привет")
        assert r.status_code > 0
        if r.status_code == 200:
            content = r.json()["choices"][0]["message"]["content"]
            assert content is None or len(content) > 0

    def test_error_structure_on_bad_model(self, client: httpx.Client):
        """Provider errors must follow OpenAI error schema."""
        r = _chat(client, "definitely-not-a-model-xyz123", "hi")
        assert r.status_code >= 400
        try:
            data = r.json()
        except json.JSONDecodeError:
            # Some error paths return non-JSON — acceptable as long as status is error
            return
        assert "error" in data, f"Missing error key: {data}"
        err = data["error"]
        assert "message" in err, f"Error missing message: {err}"

    def test_null_content_handled(self, client: httpx.Client):
        """null content in message should error cleanly."""
        payload = {
            "model": "text",
            "messages": [{"role": "user", "content": None}],
            "max_tokens": 4,
        }
        r = client.post("/v1/chat/completions", json=payload, timeout=15.0)
        # Should error, not crash
        assert r.status_code > 0


# ===================================================================
# 9. SOURCE GROUNDING VERIFICATION — batch engine integration
# ===================================================================


class TestSourceGrounding:
    """Verify source grounding in the batch engine against the live proxy.

    These tests exercise _resolve_source() and _check_grounding() integration
    through the parallel_acompletions batch functions.
    """

    @pytest.fixture(autouse=True)
    def _check_grounding_available(self):
        """Skip if rapidfuzz not installed."""
        try:
            from rapidfuzz.fuzz import token_set_ratio  # noqa: F401
        except ImportError:
            pytest.skip("rapidfuzz not installed")

    def test_resolve_source_inline_text(self):
        """_resolve_source with inline text returns text unchanged."""
        import sys
        sys.path.insert(0, "src")
        from scillm.batch import _resolve_source
        assert _resolve_source("hello world") == "hello world"

    def test_resolve_source_file_path(self, tmp_path):
        """_resolve_source with file path reads file content."""
        import sys
        sys.path.insert(0, "src")
        from scillm.batch import _resolve_source
        f = tmp_path / "source.txt"
        f.write_text("AC-17 requires multi-factor auth.", encoding="utf-8")
        result = _resolve_source(str(f))
        assert "AC-17" in result

    def test_resolve_source_list(self, tmp_path):
        """_resolve_source with list concatenates all sources."""
        import sys
        sys.path.insert(0, "src")
        from scillm.batch import _resolve_source
        f = tmp_path / "a.txt"
        f.write_text("Part A content", encoding="utf-8")
        result = _resolve_source([str(f), "Part B inline"])
        assert "Part A" in result
        assert "Part B" in result

    def test_check_grounding_high_similarity(self):
        """Identical text should score >= 0.95."""
        import sys
        sys.path.insert(0, "src")
        from scillm.batch import _check_grounding
        text = "The AC-17 control requires multi-factor authentication."
        score = _check_grounding(text, text)
        assert score >= 0.95, f"Identical text scored {score}"

    def test_check_grounding_unrelated_low(self):
        """Unrelated text should score < 0.5."""
        import sys
        sys.path.insert(0, "src")
        from scillm.batch import _check_grounding
        source = "The AC-17 control requires multi-factor authentication for remote access."
        response = "Quantum computing leverages superposition and entanglement for calculations."
        score = _check_grounding(response, source)
        assert score < 0.5, f"Unrelated text scored {score}"

    def test_check_grounding_empty_inputs(self):
        """Empty inputs should score 0.0."""
        import sys
        sys.path.insert(0, "src")
        from scillm.batch import _check_grounding
        assert _check_grounding("", "source") == 0.0
        assert _check_grounding("response", "") == 0.0

    def test_grounding_e2e_via_batch(self, any_model_live: str | None):
        """End-to-end: parallel_acompletions with source grounding on live proxy."""
        if any_model_live is None:
            pytest.skip("No live backend")

        import sys
        sys.path.insert(0, "src")
        from scillm.batch import parallel_acompletions

        source_text = (
            "The AC-17 control family governs remote access to information systems. "
            "It requires organizations to establish and document usage restrictions, "
            "configuration and connection requirements, and implementation guidance "
            "for each type of remote access allowed. Multi-factor authentication "
            "is mandatory for all remote access sessions."
        )

        requests = [
            {
                "model": any_model_live,
                "messages": [
                    {"role": "user", "content": "What does AC-17 require? Answer in one sentence."}
                ],
                "max_tokens": 64,
                "temperature": 0,
                "source": source_text,
                "grounding_threshold": 0.3,  # low threshold for test reliability
                "grounding_retries": 1,
            }
        ]

        results = asyncio.get_event_loop().run_until_complete(
            parallel_acompletions(
                requests,
                concurrency=1,
                api_base="http://127.0.0.1:4001/v1",
                api_key="sk-dev-proxy-123",
            )
        )

        assert len(results) == 1
        r = results[0]
        if r.get("status") == 200:
            # Grounding fields must be present
            assert "grounding_score" in r, f"Missing grounding_score: {r.keys()}"
            assert "grounding_attempts" in r, f"Missing grounding_attempts: {r.keys()}"
            assert isinstance(r["grounding_score"], (int, float))
            assert r["grounding_attempts"] >= 1

    def test_grounding_batch_level_source(self, any_model_live: str | None):
        """Batch-level source should apply to all requests."""
        if any_model_live is None:
            pytest.skip("No live backend")

        import sys
        sys.path.insert(0, "src")
        from scillm.batch import parallel_acompletions

        source_text = "The sky is blue because of Rayleigh scattering."

        requests = [
            {
                "model": any_model_live,
                "messages": [{"role": "user", "content": "Why is the sky blue? One sentence."}],
                "max_tokens": 32,
                "temperature": 0,
            }
        ]

        results = asyncio.get_event_loop().run_until_complete(
            parallel_acompletions(
                requests,
                source=source_text,
                grounding_threshold=0.2,
                concurrency=1,
                api_base="http://127.0.0.1:4001/v1",
                api_key="sk-dev-proxy-123",
            )
        )

        assert len(results) == 1
        r = results[0]
        if r.get("status") == 200:
            assert "grounding_score" in r
            assert r["grounding_score"] is not None

    def test_grounding_no_source_returns_none(self, any_model_live: str | None):
        """Without source, grounding fields should be None or absent."""
        if any_model_live is None:
            pytest.skip("No live backend")

        import sys
        sys.path.insert(0, "src")
        from scillm.batch import parallel_acompletions

        requests = [
            {
                "model": any_model_live,
                "messages": [{"role": "user", "content": "Say hi."}],
                "max_tokens": 8,
                "temperature": 0,
            }
        ]

        results = asyncio.get_event_loop().run_until_complete(
            parallel_acompletions(
                requests,
                concurrency=1,
                api_base="http://127.0.0.1:4001/v1",
                api_key="sk-dev-proxy-123",
            )
        )

        assert len(results) == 1
        r = results[0]
        if r.get("status") == 200:
            # Without source, grounding_score should be None
            gs = r.get("grounding_score")
            assert gs is None, f"Expected None grounding_score without source, got {gs}"


# ===================================================================
# 10. CATCH-ALL & EDGE CASES
# ===================================================================


class TestEdgeCases:
    """Miscellaneous edge cases not covered by other test classes."""

    def test_duplicate_model_field_uses_last(self, client: httpx.Client):
        """JSON with model field — verify proxy reads it correctly."""
        payload = {
            "model": "text",
            "messages": [{"role": "user", "content": "hi"}],
            "max_tokens": 4,
        }
        r = client.post("/v1/chat/completions", json=payload, timeout=15.0)
        assert r.status_code > 0

    def test_extra_fields_ignored(self, client: httpx.Client, any_model_live: str | None):
        """Unknown fields in request should be ignored, not rejected."""
        if any_model_live is None:
            pytest.skip("No live backend")
        payload = {
            "model": any_model_live,
            "messages": [{"role": "user", "content": "hi"}],
            "max_tokens": 4,
            "unknown_field_xyz": True,
            "custom_metadata": {"test": True},
        }
        r = client.post("/v1/chat/completions", json=payload, timeout=30.0)
        # Should succeed — extra fields are ignored
        assert r.status_code in (200, 400, 500, 502, 503)

    def test_zero_max_tokens(self, client: httpx.Client, any_model_live: str | None):
        """max_tokens=0 should be handled gracefully."""
        if any_model_live is None:
            pytest.skip("No live backend")
        r = _chat(client, any_model_live, "hi", max_tokens=0)
        # May return error or empty response — should not crash
        assert r.status_code > 0

    def test_rapid_sequential_requests(self, client: httpx.Client, any_model_live: str | None):
        """Rapid sequential requests should not cause connection issues."""
        if any_model_live is None:
            pytest.skip("No live backend")
        for _ in range(5):
            r = _chat(client, any_model_live, "Reply: OK")
            assert r.status_code > 0
