name: Codex Cloud Smoke (Experimental)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke:
    if: ${{ env.SCILLM_EXPERIMENTAL_CODEX_CLOUD == '1' && env.CODEX_CLOUD_API_KEY != '' }}
    runs-on: ubuntu-latest
    env:
      SCILLM_EXPERIMENTAL_CODEX_CLOUD: ${{ vars.SCILLM_EXPERIMENTAL_CODEX_CLOUD || '0' }}
      CODEX_CLOUD_API_KEY: ${{ secrets.CODEX_CLOUD_API_KEY || '' }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run chat_cloud smoke
        run: |
          python debug/smoke_codex_cloud_chat.py

