name: Copilot Review Notify
on:
  pull_request_review:
    types: [submitted]
permissions:
  pull-requests: write
  statuses: write
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Mark status when Copilot reviews
        if: github.event.review.user.login == 'github-copilot[bot]'
        run: |
          PR_SHA="${{ github.event.pull_request.head.sha }}"
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${PR_SHA} \
            -d '{"state":"success","context":"copilot/review","description":"Copilot reviewed this PR"}'
      - name: Comment summary
        if: github.event.review.user.login == 'github-copilot[bot]'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "Copilot reviewed this PR. Status set to `copilot/review = success`."
            })

