name: Notebooks Smoke

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pip install uv
      - name: Sync env
        run: |
          uv venv .venv
          . .venv/bin/activate
          uv pip install -e .[dev]
          uv pip install nbconvert nest_asyncio
      - name: Run notebooks smoke (CI subset)
        run: |
          . .venv/bin/activate
          make notebooks-smoke-ci

